#Assymetric key setup

#encrypt:
##  keyStore:
#   location: classpath:/server.jks
#   password: passw0rd
#   alias: testkey
#   secret: passw0rd
   
   # symmetric key setup

management:
  security:
    enabled: false    


encrypt:
        key: abc
    
  